### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by iSentrie** [atiysuu/aty_icehud#2]
Hi, check #1 

1. `WaitPlayer()` is not needed at all for ESX and probably for QB too, its a huge performance issue for it, since you use ESX export to get all data you gonna need, you dont need to call it in your loops and kill performance. 

with that function in vehicle:
![image](https://user-images.githubusercontent.com/29688478/221428298-f503ff5d-a4df-450a-98bf-4cfead440eea.png)

without while in vehicle:
![image](https://user-images.githubusercontent.com/29688478/221428339-6cbdee0e-0c89-4dca-aa1c-efc51fd24616.png)

**Comment by atiysuu** [comment]
I took this function from my old projects and i didn't realize it dropped that much

**Comment by iSentrie** [comment]
👍
